# coding: utf-8

# flake8: noqa
"""
    KFServing

    Python SDK for KFServing  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from kfserving.models.v1alpha2_alibi_explainer_spec import V1alpha2AlibiExplainerSpec
from kfserving.models.v1alpha2_batcher import V1alpha2Batcher
from kfserving.models.v1alpha2_custom_spec import V1alpha2CustomSpec
from kfserving.models.v1alpha2_deployment_spec import V1alpha2DeploymentSpec
from kfserving.models.v1alpha2_endpoint_spec import V1alpha2EndpointSpec
from kfserving.models.v1alpha2_explainer_spec import V1alpha2ExplainerSpec
from kfserving.models.v1alpha2_inference_service import V1alpha2InferenceService
from kfserving.models.v1alpha2_inference_service_list import V1alpha2InferenceServiceList
from kfserving.models.v1alpha2_inference_service_spec import V1alpha2InferenceServiceSpec
from kfserving.models.v1alpha2_inference_service_status import V1alpha2InferenceServiceStatus
from kfserving.models.v1alpha2_light_gbm_spec import V1alpha2LightGBMSpec
from kfserving.models.v1alpha2_logger import V1alpha2Logger
from kfserving.models.v1alpha2_onnx_spec import V1alpha2ONNXSpec
from kfserving.models.v1alpha2_predictor_spec import V1alpha2PredictorSpec
from kfserving.models.v1alpha2_py_torch_spec import V1alpha2PyTorchSpec
from kfserving.models.v1alpha2_sk_learn_spec import V1alpha2SKLearnSpec
from kfserving.models.v1alpha2_status_configuration_spec import V1alpha2StatusConfigurationSpec
from kfserving.models.v1alpha2_tensorflow_spec import V1alpha2TensorflowSpec
from kfserving.models.v1alpha2_transformer_spec import V1alpha2TransformerSpec
from kfserving.models.v1alpha2_triton_spec import V1alpha2TritonSpec
from kfserving.models.v1alpha2_xg_boost_spec import V1alpha2XGBoostSpec
